### ISSUE TITLE
 init script not working on windows

### ISSUE THREAD

**Issue by giji** [subzerocloud/subzero-cli#32] opened 2018-09-14 22:03 UTC
Hello 
on Windows 10 64bit. I followed all the steps described on the corresponding GitHub page and subzero base-project which takes me through the questions and finishes with "Downloading the base project..". But my project directory always stays empty afterwards. Switching between between the options (subzero or pure postgrest, database structure/migrations here yes/no) makes no difference, neither does running it within a Powershell session with admin privileges.

**Comment by giji** [comment] 2018-09-24 08:50
@ruslantalpa   no, still not working 
does not work :
base project 
dashboard 
works:
watch 

if launching  directly respective CMD's seems partly to work
 the problem i think is in commander package/commands
will try to find a problem

**Comment by ruslantalpa** [comment] 2018-09-27 11:57
quite disappointed to find out the root of the problem is in a popular node module and it simply does not work on windows :(
there is a PR waiting to be merged for over a year https://github.com/tj/commander.js/pull/604
I guess i'll have to fork and fix it myself

**Comment by giji** [comment] 2018-09-27 13:32
@ruslantalpa 
no i have docker installed on hyper-v , anyway latest Windows 10 has hyper-v installed i have installed Ubuntu vm inside and then docker and then subzero works flawlessly, i would recomend to leave this way and wait until the change will go upstream.
p.s do you still need docker info ?

**Comment by ruslantalpa** [comment] 2018-09-27 14:38
since last post I discovered another bunch of bugs and fixed them.
docker info (especially from your windows pro with hyper-v) will help since I have some special logic to distinguish between the two scenarios.

i'll have the fixes up this week. Thank you for the  feedback

**Comment by giji** [comment] 2018-10-04 20:43
Hello Russian sorry i was out, sure i will test and get back to you.

**Comment by giji** [comment] 2018-10-05 21:38
Works flawlessly :) 👍

**Comment by ruslantalpa** [comment] 2018-10-15 06:06
there is a new release `v0.1.25` so hopefully this is solved, + I recently moved to windows so i'll be able to catch these problems faster :)
thank you for the feedback

**Closed by ruslantalpa** 2018-10-15 06:06 UTC

**Comment by toubsen** [comment] 2019-03-07 22:27
I'm seeing the same problem with 0.1.28 on Windows 10 Home with Docker Toolbox.
